Add newline detection in ili9341_draw_string()
ardnew/ILI9341-STM32-HAL pull request #6
Opened 2021-07-19 08:39 UTC by IboKhaled

The characters after a newline will be printed in the next line

2021-07-20 12:22 UTC, ardnew requested changes

2021-07-20 12:22 UTC, ardnew commented on ILI9341/ili9341_gfx.c
> +    {
I don't have a device setup to test this off-hand, but perhaps a small modification would support each `\n`, `\r`, and `\r\n`?

```c
    if ('\r' == *str) {
      curr_x = start_x;
    } 
    else if ('\n' == *str) {
      curr_y += attr.font->height;
      curr_x = start_x;
    } 
    else {
```

If `\r\n` is seen, then `curr_x = start_x;` gets evaluated twice, but I think its worth it for the simplicity of the logic.

Can you verify this works and update? Or make any changes needed if its close?

2021-07-21 07:10 UTC, IboKhaled commented on ILI9341/ili9341_gfx.c
> +    {
Yes, works fine, updated!

2021-07-22 14:18 UTC, ardnew commented
Looks good, merging. 

Thank you @IboKhaled for yet another solid update

2021-07-22 14:18 UTC, merged